web0/mobile/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from mobile import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<soul_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^submit', views.submit, name='submit'),
    url(r'^postJson$', views.postJson, name='postJson'),
]

web0/web0/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import autocomplete_light

autocomplete_light.autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'web0.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^mobile/', include('mobile.urls',namespace="mobile")),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
)

urlpatterns += staticfiles_urlpatterns()

web0/mobile/models.py
from django.db import models

# Create your models here.

class Soul(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True, unique=True)
    city = models.TextField(null=True, blank=True)
    state = models.TextField(null=True, blank=True)
    event = models.TextField(null=True, blank=True)
    date = models.DateField('distributed',null=True, blank=True)
    book = models.CharField(max_length=400, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    distributor = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

web0/mobile/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from mobile.models import Soul
import json
from django.core import serializers

# Create your views here.



def index(request):
    latest_soul_list = Soul.objects.all()
    context = {'latest_soul_list':latest_soul_list}
    return render(request,'mobile/index.html',context)


def detail(request, soul_id):
    soul = get_object_or_404(Soul, pk=soul_id)
    return render(request, 'mobile/detail.html', {'soul': soul})

@csrf_exempt
def submit(request):
    try:
        json_data = request.read()
        numRecords = numErrors = 0
        errorMessage = ""
        for obj in serializers.deserialize("json",json_data):
            try:
                obj.save()
                numRecords = numRecords+1
            except Exception as e:
                errorMessage = errorMessage+"\n\r"+str(e)+" "+str(type(e))
                numErrors = numErrors + 1
        return render(request,'mobile/submitSuccess.html',{'numRecords':numRecords,'numErrors':numErrors,'errorMessage':errorMessage})
    except KeyError:
        return render(request,'mobile/missingData.html',{})


### Utilities below are for internal usage only.
def postJson(request):
    import urllib2
    # Whatever structure you need to send goes here:
    jdata = json.dumps({"username":"abc", "password":"def"})
    urllib2.urlopen("http://127.0.0.1:8000/mobile/submit", jdata)

web0/mobile/templates/mobile/base.html
{% load staticfiles %}

<html>
  <head>
    <script src="{% static 'jquery-1.10.2.min.js' %}"></script>

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}"
          rel="stylesheet" media="screen">
    
    <script src="{% static 'DataTables/media/js/jquery.dataTables.js' %}"></script>
    <link href="{% static 'DataTables/media/css/jquery.dataTables.css' %}"
          rel="stylesheet" media="screen">

    <script src="{% static 'DataTables/extensions/TableTools/js/dataTables.tableTools.js' %}"></script>
    <link href="{% static 'DataTables/extensions/TableTools/css/dataTables.tableTools.css' %}"
          rel="stylesheet" media="screen">
  </head>

  <body>
    {% block content %}
    {% endblock %}

    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

web0/mobile/templates/mobile/detail.html
<ol style="list-style-type:none">
<li>{{soul.id}}</li>
<li>{{soul.name}}</li>
<li>{{soul.street}}</li>
<li>{{soul.city}}</li>
<li>{{soul.state}}</li>
<li>{{soul.book}}</li>
<li>{{soul.distributor}}</li>
<li>{{soul.description}}</li>
</ol>

web0/mobile/templates/mobile/index.html
{% extends "mobile/base.html" %}
{% load staticfiles %}

{% block content %}
<H1>This4Bliss Contacts Server</H1>


<style media="screen" type="text/css">

table
{
border-collapse:collapse;
}
table, th, td
{
border: 1px solid black;
}

</style>
{% if latest_soul_list %}
	<table id="example" class="display" cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
            <th>City</th>
            <th>State</th>
            <th>Event</th>
			<th>Date</th>
			<th>Distributor</th>
		</tr>
	</thead>
	<tbody>
    {% for soul in latest_soul_list %}
    	<tr>
    		<td><a href="{% url 'mobile:detail' soul.id%}">{{soul.name}}</a></td>
    		<td>{{soul.email}}</td>
            <td>{{soul.city}}</td>
            <td>{{soul.state}}</td>
            <td>{{soul.event}}</td>
    		<td>{{soul.date}}</td>
    		<td>{{soul.distributor}}</td>
    	</tr>
    {% endfor %}
    </tbody>
    </table>
{% else %}
    <p>No souls!</p>
{% endif %}

<script type="text/javascript">
   $(document).ready(function() {
        $('#example').DataTable( {
            dom: 'T<"clear">lfrtip',
            
            tableTools: {
                "sRowSelect": "multi",
                "aButtons": [ "select_all", "select_none" ],
                "aButtons": [ "copy", "csv" ],
                "aButtons": [
                    {
                    "sExtends": "copy",
                    "sButtonText": "Copy to clipboard",
                    "bSelectedOnly": true,
                    "oSelectorOpts": {
                        filter: "applied"
                        },
                    },
                    {
                    "sExtends": "csv",
                    "sButtonText": "Download CSV",
                    "bSelectedOnly": true,
                    "oSelectorOpts": {
                        filter: "applied"
                        },
                    },
    
                ],
                "sSwfPath": "{% static 'DataTables/extensions/TableTools/swf/copy_csv_xls.swf' %}"
            }
        } );
    } );
</script>

<H5>contact sidharth.chhabra@gmail.com for any issues</H5>
{% endblock %}

web0/mobile/templates/mobile/missingData.html
Records weren't submitted. 

web0/mobile/templates/mobile/missingdata.html
Records weren't submitted. 

web0/mobile/templates/mobile/submitSuccess.html
{{numRecords}} records were submitted successfully.
There were errors with {{numErrors}} records. 
</br>{{errorMessage}}
Please check the <a href="{% url 'mobile:index' %}"> log </a> for successful records.